CREATE TABLE silver.dim_UF (
    id INT IDENTITY(1, 1) PRIMARY KEY,
    Estado VARCHAR(25),
    UF VARCHAR(20),
    Regiao VARCHAR(25),
    Populacao INT
);

CREATE TABLE silver.dim_Candidato (
    id_candidato INT IDENTITY(1, 1) PRIMARY KEY,
    Cargo VARCHAR(100),
    Coligacao VARCHAR(100),
    Cor_Raca VARCHAR(25),
    Situacao_Candidato VARCHAR(100),
    Estado_civil VARCHAR(25),
    Faixa_Etaria VARCHAR(25),
    Genero VARCHAR(10),
    Grau_instrucao VARCHAR(50),
    Municipio VARCHAR(50),
    Ocupacao VARCHAR(50),
    Reeleicao VARCHAR(10),
    Sigla_Partido VARCHAR(10),
    Cadastramento VARCHAR(25),
    Candidatura VARCHAR(25),
    Situacao_de_totalizacao VARCHAR(25),
    Turno INT,
    UF VARCHAR(20),
    id_UF INT,
    Data DATETIME,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Comparecimento_Abstencao (
    Estado_civil VARCHAR(25),
    Faixa_Etaria VARCHAR(25),
    Genero VARCHAR(10),
    Escolaridade VARCHAR(25),
    Municipio VARCHAR(100),
    Pais VARCHAR(25),
    Regiao VARCHAR(25),
    Turno INT,
    UF VARCHAR(20),
    id_UF INT,
    Zona INT,
    QtdEleitorDeficienteAbstencao INT,
    QtdEleitorComparecimentoTTE INT,
    QtdEleitorAbstencaoTTE INT,
    QtdEleitores_Aptos INT,
    QtdEleitorAbstencao INT,
    QtdEleitorComparecimento INT,
    Data DATETIME,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Detalhe_Votacao (
    Zona INT,
    Cargo VARCHAR(50),
    Codigo_Municipio VARCHAR(25),
    Municipio VARCHAR(50),
    Turno INT,
    UF VARCHAR(20),
    id_UF INT,
    QtdVotosBrancos INT,
    Qtd_Votos_Validos_Legendas INT,
    Qtd_Comparecimento INT,
    Qtd_Votos_Anulados INT,
    Qtd_Votos_Validos_Nominais INT,
    Qtd_Secoes_Agregadas INT,
    Qtd_Votos_Validos INT,
    Qtd_Aptos_Totalizados INT,
    Qtd_Total_Secoes INT,
    Votos_Nulos INT,
    Votos_Totais INT,
    Qtd_Aptos INT,
    Qtd_Secoes_Principais INT,
    Abstencoes INT,
    Votos_Legendas_Validos INT,
    Qtd_Votos_Nulos_Tecnico INT,
    Votos_Anulados_Subjudice INT,
    Votos_Concorrentes INT,
    Votos_Nulos INT,
    Votos_Nominais_Anulados INT,
    Secoes_Instaladas INT,
    Data DATETIME,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Fundo_Partidario (
    UF VARCHAR(20),
    id_UF INT,
    Cor_Raca VARCHAR(25),
    Esfera_Partidaria VARCHAR(25),
    Genero VARCHAR(10),
    Partido VARCHAR(25),
    Qtd_Candidatos INT,
    Valor_FP_Aplicado_Campanha DECIMAL(10,2),
    Recursos_Declarados DECIMAL(10,2),
    Data DATETIME,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Pesquisas_Eleitorais (
    UF VARCHAR(20),
    id_UF INT,
    Municipio VARCHAR(50),
    Protocolo_Registro VARCHAR(50),
    Regiao VARCHAR(25),
    Codigo_Registro_CONRE VARCHAR(50),
    Dados_Municipes VARCHAR(100),
    Fim_Pesquisa DATETIME,
    Inicio_Pesquisa DATETIME,
    Registro DATETIME,
    Estatistico_Resp VARCHAR(50),
    Metodologia_Pesq VARCHAR(100),
    Empresa_Nome_Fantasia VARCHAR(100),
    Plano_Amostral VARCHAR(100),
    Sistema_Controle VARCHAR(100),
    Qtd_Pesq INT,
    Qtd_Entrevistados INT,
    Valor DECIMAL(10,2),
    Data DATETIME,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Quociente_Eleitoral (
    Cargo VARCHAR(25),
    Municipio VARCHAR(50),
    Turno INT,
    UF VARCHAR(20),
    Coligacao VARCHAR(50),
    Qtd_Vagas_QE INT,
    Qtd_Votos_Legenda_QE INT,
    Qtd_Votos_Nominais_QE INT,
    Qtd_Votos_Validos_QE INT,
    Valor_Quociente_Eleitoral INT,
    Qtd_Votos_Legenda_QP INT,
    Qtd_Votos_Nominais_QP INT,
    Qtd_Vagas_Preenchidas_QP INT,
    Qtd_Vagas_Media_QP INT,
    Qtd_Vagas_Obtidas_QP INT,
    Qtd_Votos_Coligacao_QP INT,
    Data DATETIME,
    id_UF INT,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Receita_Candidatos (
    UF VARCHAR(20),
    Esfera_Partidaria VARCHAR(25),
    Partido VARCHAR(25),
    Cargo VARCHAR(25),
    Esfera VARCHAR(25),
    Especie_Receita VARCHAR(25),
    Fonte_Receita VARCHAR(25),
    Municipio VARCHAR(50),
    Nome_Candidato VARCHAR(50),
    Nome_Doador VARCHAR(50),
    Origem_Receita VARCHAR(25),
    Quilombola VARCHAR(25),
    Situacao_Candidatura VARCHAR(25),
    Situacao_Julgamento VARCHAR(25),
    Situacao_Totalizacao VARCHAR(25),
    Valor_Receita DECIMAL(10,2),
    Data DATETIME,
    id_UF INT,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);

CREATE TABLE silver.dim_Votacao_Candidato (
    id_votacao_candidato INT IDENTITY(1, 1) PRIMARY KEY,
    Cargo VARCHAR(50),
    Municipio VARCHAR(50),
    Turno INT,
    UF VARCHAR(20),
    Codigo_Municipio VARCHAR(25),
    Cor_Raca VARCHAR(25),
    Estado_Civil VARCHAR(25),
    Faixa_Etaria VARCHAR(25),
    Genero VARCHAR(10),
    Grau_Instrucao VARCHAR(25),
    Nome_Candidato VARCHAR(50),
    Numero_Candidato VARCHAR(50),
    Ocupacao VARCHAR(50),
    Partido VARCHAR(25),
    Situacao_Totalizacao VARCHAR(25),
    Zona INT,
    Qtd_Votos_Validos INT,
    Qtd_Votos_Nominais INT,
    Data DATETIME,
    id_UF INT,
    FOREIGN KEY (id_UF) REFERENCES dim_UF(id)
);
